affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 30
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 15
symbolic.funs_name.0:
- - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
- - x
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
- - x
  - x
  - '0'
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - x
  - '0'
  - x
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - '0'
  - '0'
  - x^2
  - '0'
  - '0'
  - x
  - '0'
symbolic.funs_name.1:
- - '0'
  - x
  - x
  - x
- - x
  - x
  - x
  - x
- - '0'
  - x
  - x
  - x
- - '0'
  - '0'
  - x
  - x
- - '0'
  - '0'
  - '0'
  - x
- - '0'
  - x
  - x
  - x
- - '0'
  - x
  - x
  - x
- - '0'
  - x
  - x
  - x
- - x
  - x
  - x
  - x
- - '0'
  - x
  - x
  - x
symbolic.funs_name.2:
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
symbolic_enabled: true
width:
- - 25
  - 0
- - 4
  - 0
- - 10
  - 0
- - 1
  - 0
