affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda
grid: 20
grid_eps: 0.02
grid_range:
- -1
- 1
k: 3
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 9
symbolic.funs_name.0:
- - x
  - '0'
  - x
  - '0'
  - x
  - x
  - x
  - x
  - tan
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - tan
  - x
  - x
  - x
  - '0'
  - x
- - x
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - tan
  - '0'
  - x
  - x
  - x
  - '0'
- - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - tan
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - '0'
  - '0'
  - '0'
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - tan
  - x
  - x
  - '0'
  - x
  - x
- - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - '0'
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - '0'
  - '0'
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - tan
  - '0'
  - '0'
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - '0'
  - exp
  - x
  - x
  - x
  - x
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
symbolic.funs_name.1:
- - '0'
  - '0'
  - x
  - x
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - '0'
  - x
  - x
  - '0'
  - '0'
  - '0'
- - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - sin
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - '0'
  - sin
  - x
  - x
  - '0'
  - x
  - '0'
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
- - x
  - sin
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
  - x
symbolic.funs_name.2:
- - x
  - x
  - x
  - x
symbolic_enabled: true
width:
- - 14
  - 0
- - 17
  - 0
- - 4
  - 0
- - 1
  - 0
